/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Kalkulator;

/**
 *
 * @author Daniel Haqeem
 */
public class Kalkulator extends javax.swing.JFrame {

    /**
     * Creates new form Kalkulator
     */
    public Kalkulator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        KalkulatorResult = new javax.swing.JTextField();
        kalkButton9 = new javax.swing.JButton();
        kalkButton7 = new javax.swing.JButton();
        kalkEqual = new javax.swing.JButton();
        kalkButton8 = new javax.swing.JButton();
        kalkButton4 = new javax.swing.JButton();
        kalkButton5 = new javax.swing.JButton();
        kalkButton6 = new javax.swing.JButton();
        kalkButton3 = new javax.swing.JButton();
        kalkButton2 = new javax.swing.JButton();
        kalkButton1 = new javax.swing.JButton();
        kalkButton0 = new javax.swing.JButton();
        button_Clear = new javax.swing.JButton();
        kalkmulti_Button = new javax.swing.JButton();
        kalkadd_Button = new javax.swing.JButton();
        kalkminus_Button = new javax.swing.JButton();
        kalkdivide_Button = new javax.swing.JButton();

        jButton3.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        KalkulatorResult.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        KalkulatorResult.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        KalkulatorResult.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(KalkulatorResult, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 260, 70));

        kalkButton9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        kalkButton9.setText("9");
        kalkButton9.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(kalkButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 70, 50));

        kalkButton7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        kalkButton7.setText("7");
        kalkButton7.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        kalkButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kalkButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(kalkButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 70, 50));

        kalkEqual.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        kalkEqual.setText("=");
        kalkEqual.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(kalkEqual, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 360, 70, 50));

        kalkButton8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        kalkButton8.setText("8");
        kalkButton8.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(kalkButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 70, 50));

        kalkButton4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        kalkButton4.setText("4");
        kalkButton4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(kalkButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 70, 50));

        kalkButton5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        kalkButton5.setText("5");
        kalkButton5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(kalkButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, 70, 50));

        kalkButton6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        kalkButton6.setText("6");
        kalkButton6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(kalkButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, 70, 50));

        kalkButton3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        kalkButton3.setText("3");
        kalkButton3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(kalkButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 290, 70, 50));

        kalkButton2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        kalkButton2.setText("2");
        kalkButton2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(kalkButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 290, 70, 50));

        kalkButton1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        kalkButton1.setText("1");
        kalkButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(kalkButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 70, 50));

        kalkButton0.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        kalkButton0.setText("0");
        kalkButton0.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(kalkButton0, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 360, 70, 50));

        button_Clear.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        button_Clear.setText("C");
        button_Clear.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(button_Clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 70, 50));

        kalkmulti_Button.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        kalkmulti_Button.setText("x");
        kalkmulti_Button.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(kalkmulti_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, 40, 30));

        kalkadd_Button.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        kalkadd_Button.setText("+");
        kalkadd_Button.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(kalkadd_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 40, 30));

        kalkminus_Button.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        kalkminus_Button.setText("-");
        kalkminus_Button.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(kalkminus_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 40, 30));

        kalkdivide_Button.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        kalkdivide_Button.setText("÷");
        kalkdivide_Button.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(kalkdivide_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 40, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void kalkButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kalkButton7ActionPerformed
        EnterNumbers("7");
    }//GEN-LAST:event_kalkButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    
    private void EnterNumbers(String q){
        String Nums = KalkulatorResult.getText()+ q;
        KalkulatorResult.setText(Nums);
    }
    private void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Kalkulator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField KalkulatorResult;
    private javax.swing.JButton button_Clear;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton kalkButton0;
    private javax.swing.JButton kalkButton1;
    private javax.swing.JButton kalkButton2;
    private javax.swing.JButton kalkButton3;
    private javax.swing.JButton kalkButton4;
    private javax.swing.JButton kalkButton5;
    private javax.swing.JButton kalkButton6;
    private javax.swing.JButton kalkButton7;
    private javax.swing.JButton kalkButton8;
    private javax.swing.JButton kalkButton9;
    private javax.swing.JButton kalkEqual;
    private javax.swing.JButton kalkadd_Button;
    private javax.swing.JButton kalkdivide_Button;
    private javax.swing.JButton kalkminus_Button;
    private javax.swing.JButton kalkmulti_Button;
    // End of variables declaration//GEN-END:variables
}
